# Generated by Django 3.2.4 on 2022-02-26 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20220219_0857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='space',
            name='price',
            field=models.IntegerField(),
        ),
    ]
